apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
       containers:
        - name: postgre
          image: postgres:15.0
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "Pg#123"
          - name: POSTGRES_USER
            value: "kubnews"
          - name: POSTGRES_DB
            value: "kubnews"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
       containers:
        - name: web
          image: osnioliveira/kube-news:{{TAG}}
          ports:
          - containerPort: 8080
          env:
          - name: DB_PASSWORD
            value: "Pg#123"
          - name: DB_USERNAME
            value: "kubnews"
          - name: DB_DATABASE
            value: "kubnews"
          - name: DB_HOST
            value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer